version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3312:3306"
###< doctrine/doctrine-bundle ###
  webserver:
    ports:
      - "8080:80"
    extra_hosts:
      - "database:192.168.0.105"

  mailer:
    ports:
      - "8025:8025"
      - "1025:1025"

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
